feat(*) add rule no structure correct
Nyaran/gplint pull request #438
Opened 2023-07-12 08:21 UTC by AlexisArteaga13

Saludos!! Envío una nueva regla para mantener la estructura del escenario con el orden de las palabras claves conocidas, Given, When, Then.

2023-07-14 18:53 UTC, Nyaran commented
Buenas:

Ya existe una regla que realiza parcialmente lo que quieres: `keywords-in-logical-order`

Esa regla valida que los steps estén en el orden lógico, puedes mejorarla añadiendo la propiedad de configuración `detectMissingKeywords` (por defecto su valor debería ser `false` para que se mantenga el funcionamiento actual)

2023-07-15 08:20 UTC, AlexisArteaga13 commented
> Buenas:
> 
> Ya existe una regla que realiza parcialmente lo que quieres: `keywords-in-logical-order`
> 
> Esa regla valida que los steps estén en el orden lógico, puedes mejorarla añadiendo la propiedad de configuración `detectMissingKeywords` (por defecto su valor debería ser `false` para que se mantenga el funcionamiento actual)

Corregido!! , elimine las reglas y actualicé la regla existente

2023-07-15 08:27 UTC, Nyaran requested changes

2023-07-15 08:27 UTC, Nyaran commented on src/rules/no-structure-correct.ts
Este fichero ya no sería necesario, borralo

2023-07-15 08:27 UTC, Nyaran commented on test/rules/keywords-in-logical-order/keywords-in-logical-order.ts
> +        messageElements: { scenario: 'Scenario outline without Then', missingKeywords: 'when' },
Aquí pone que no tiene `Then`, pero en `missingKeywords` has puesto `when`, ¿es correcto?

2023-07-15 08:27 UTC, Nyaran commented on test/rules/keywords-in-logical-order/keywords-in-logical-order.ts
> +describe('Keywords in logical order', function () {
Aunque no es problemático realmente, intenta evitar que tu IDE manipule los estilos añadiendo espacios (si usas VSCode es una de sus opciones), así se facilita la revisión

2023-07-15 08:32 UTC, AlexisArteaga13 commented on test/rules/keywords-in-logical-order/keywords-in-logical-order.ts
> +        messageElements: { scenario: 'Scenario outline without Then', missingKeywords: 'when' },
Tienes razón, error de mano, ahora subo el fix

2023-07-15 08:36 UTC, AlexisArteaga13 commented on test/rules/keywords-in-logical-order/keywords-in-logical-order.ts
> +describe('Keywords in logical order', function () {
Gracias por la recomendación, lo tomo en cuenta.

2023-07-15 09:08 UTC, Nyaran requested changes

2023-07-15 09:08 UTC, Nyaran commented on src/rules/keywords-in-logical-order.ts
> +    if (detectMissingKeywords && child.scenario && !Object.values(existsKeyword).every((value) => value === true)) {
Redudante el evaluar un boolean así
```suggestion
    if (detectMissingKeywords && child.scenario && !Object.values(existsKeyword).every((value) => value)) {
```

2023-07-15 17:37 UTC, Nyaran approved these changes

2023-07-15 17:37 UTC, merged